name: Test Branch Deletion

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged || github.event.pull_request.merged_by
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          branch_name=$(echo "${{ github.event.pull_request.head.ref }}")
          echo "Branch name: $branch_name"  # Debug log
          git push --delete origin $branch_name
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
