name: Delete Branch After Merge

on:
  pull_request:
    types:
      - closed

jobs:
  delete_branch_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          git push --delete origin ${{ github.head_ref }}
