name: Delete Branch on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged || github.event.pull_request.merged_by
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Debug Log
        run: |
          echo "PAT_TOKEN: ${{ secrets.PAT_TOKEN }}"
          echo "GitHub Token: ${{ secrets.GITHUB_TOKEN }}"
          branch_name=$(echo "${{ github.event.pull_request.head.ref }}")
          echo "Branch name: $branch_name"
          git push --delete origin $branch_name
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
